/**
 * Typed client of the Django API (types generated by `npm run api:generate` from
 * /api/schema/ into schema.d.ts — never edit that file by hand).
 *
 * The browser calls /api/* on the web origin; Next.js forwards it to the backend.
 * Sign-in tokens live in httpOnly cookies: this code never reads them.
 */
import createClient, { type Middleware } from "openapi-fetch";

import type { components, paths } from "./schema";

export type Schemas = components["schemas"];

export type ApiErrorBody = {
  code?: string;
  message?: string;
  fields?: Record<string, string[] | string>;
  attempts_left?: number;
  retry_after?: number;
};

export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: string = "error",
    public readonly body: ApiErrorBody = {},
  ) {
    super(body.message || `API error ${status} (${code})`);
    this.name = "ApiError";
  }

  /** First message of a field error, or the general message. */
  fieldMessage(field: string): string | undefined {
    const value = this.body.fields?.[field];
    return Array.isArray(value) ? value[0] : value;
  }
}

/** Sent on every call: lets the backend refuse cross-site requests made with our cookies. */
export const CLIENT_HEADER = { "X-SG-Client": "web" } as const;

function currentLocale(): string {
  return typeof document === "undefined" ? "fr" : document.documentElement.lang || "fr";
}

/** True when a session cookie exists (set by the backend, holds no secret). */
export function hasSession(): boolean {
  return typeof document !== "undefined" && /(?:^|;\s*)sg_signed_in=1/.test(document.cookie);
}

let refreshing: Promise<boolean> | null = null;

/** Renews the session cookies once, shared by every call that needs it. */
function refreshSession(): Promise<boolean> {
  refreshing ??= fetch(`${origin()}/api/v1/auth/refresh`, {
    method: "POST",
    credentials: "same-origin",
    headers: { ...CLIENT_HEADER },
  })
    .then((response) => response.ok)
    .catch(() => false)
    .finally(() => {
      refreshing = null;
    });
  return refreshing;
}

function origin(): string {
  return typeof window === "undefined" ? "http://localhost" : window.location.origin;
}

// Copies of the requests, so a call can be sent again after the session is renewed.
const retryCopies = new WeakMap<Request, Request>();

const sessionMiddleware: Middleware = {
  onRequest({ request }) {
    request.headers.set("Accept-Language", currentLocale());
    for (const [name, value] of Object.entries(CLIENT_HEADER)) request.headers.set(name, value);
    retryCopies.set(request, request.clone());
    return request;
  },
  async onResponse({ request, response }) {
    const path = new URL(request.url).pathname;
    if (response.status !== 401 || path.startsWith("/api/v1/auth/") || !hasSession()) {
      return response;
    }
    const copy = retryCopies.get(request);
    if (copy && (await refreshSession())) return fetch(copy);
    return response;
  },
};

export const api = createClient<paths>({
  baseUrl: origin(),
  credentials: "same-origin",
  // Looked up at each call (not captured once): lets tests and polyfills replace fetch.
  fetch: (request) => globalThis.fetch(request),
  // FormData (uploads) goes as is; everything else as JSON.
  bodySerializer: (body: unknown) => (body instanceof FormData ? body : JSON.stringify(body)),
});
api.use(sessionMiddleware);

/** Returns the data of a call, or throws an ApiError with the backend message. */
export async function unwrap<T>(
  call: Promise<{ data?: T; error?: unknown; response: Response }>,
): Promise<T> {
  const { data, error, response } = await call;
  if (!response.ok) {
    const body = (error ?? {}) as ApiErrorBody;
    throw new ApiError(response.status, body.code, body);
  }
  return data as T;
}
