/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_logout_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout-all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_logout_all_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/otp/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a 6-digit code by WhatsApp, SMS or e-mail (sign-up and sign-in). */
    post: operations["auth_otp_request_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/otp/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_otp_verify_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_password_login_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Rotate the tokens from the refresh cookie (the old refresh token is blacklisted). */
    post: operations["auth_refresh_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/countries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Countries open on the platform (phone prefixes, default currency). */
    get: operations["countries_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/guest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["guest_retrieve"];
    put?: never;
    post: operations["guest_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Liveness probe used by Docker, the web app and monitoring. */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me_retrieve"];
    put?: never;
    post?: never;
    /** @description Asks for deletion: erased after the grace period unless she signs in again. */
    delete: operations["me_destroy"];
    options?: never;
    head?: never;
    patch: operations["me_partial_update"];
    trace?: never;
  };
  "/api/v1/me/contact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a code to a new number or e-mail before changing it. */
    post: operations["me_contact_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/contact/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["me_contact_confirm_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/onboarding": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["me_onboarding_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["me_password_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/photo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description New profile photo: processed in the background (status "processing" then "ready"). */
    post: operations["me_photo_create"];
    delete: operations["me_photo_destroy"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/media": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["media_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/media/{asset_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["media_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["notifications_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/push/key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["notifications_push_key_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/push/subscriptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["notifications_push_subscriptions_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/push/unsubscribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["notifications_push_unsubscribe_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["notifications_read_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Sends a test notification to oneself (to try phone alerts). */
    post: operations["notifications_test_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/unread-count": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["notifications_unread_count_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/trades": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Trades offered at sign-up and in search, in the language of the request. */
    get: operations["trades_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description * `whatsapp` - whatsapp
     *     * `sms` - sms
     *     * `email` - email
     *     * `console` - console
     * @enum {string}
     */
    ChannelEnum: "whatsapp" | "sms" | "email" | "console";
    CodeRequestRequest: {
      phone?: string;
      email?: string;
      locale?: components["schemas"]["LanguageEnum"];
    };
    CodeRequestResult: {
      /** Format: uuid */
      challenge_id: string;
      channel: components["schemas"]["ChannelEnum"];
      /** @description Seconds before a new code can be asked. */
      resend_after: number;
      /** @description Seconds before the code expires. */
      expires_in: number;
    };
    CodeVerifyRequest: {
      /** Format: uuid */
      challenge_id: string;
      code: string;
      locale?: components["schemas"]["LanguageEnum"];
    };
    ContactChangeConfirmRequest: {
      /** Format: uuid */
      challenge_id: string;
      code: string;
    };
    ContactChangeRequestRequest: {
      phone?: string;
      email?: string;
      locale?: components["schemas"]["LanguageEnum"];
    };
    Country: {
      /** @description ISO 3166-1 alpha-2 code, e.g. BJ or FR. */
      code: string;
      name: string;
      phone_prefix: string;
      /** @description ISO 4217 code, e.g. XOF or EUR. */
      readonly default_currency: string;
    };
    DeletionScheduled: {
      /**
       * Format: date-time
       * @description Signing in again before this date keeps the account.
       */
      erase_after: string;
    };
    Guest: {
      /** Format: uuid */
      readonly id: string;
      first_name: string;
      phone: string;
    };
    GuestRequest: {
      first_name: string;
      phone: string;
    };
    Health: {
      status: string;
    };
    /**
     * @description * `makeup` - Lipstick
     *     * `hair` - Comb
     *     * `braids` - Braid
     *     * `nails` - Nail polish
     *     * `sewing` - Thread spool
     *     * `headwrap` - Headwrap
     *     * `skincare` - Cream jar
     * @enum {string}
     */
    IconEnum: "makeup" | "hair" | "braids" | "nails" | "sewing" | "headwrap" | "skincare";
    /**
     * @description * `image` - image
     *     * `video` - video
     *     * `audio` - audio
     * @enum {string}
     */
    KindEnum: "image" | "video" | "audio";
    /**
     * @description * `fr` - French
     *     * `en` - English
     *     * `sk` - Slovak
     * @enum {string}
     */
    LanguageEnum: "fr" | "en" | "sk";
    MarkReadRequest: {
      /** @description Leave out to mark everything as read. */
      ids?: string[];
    };
    Me: {
      /** Format: uuid */
      readonly id: string;
      readonly phone: string | null;
      /** Format: email */
      readonly email: string | null;
      first_name: string;
      last_name: string;
      /** Format: date */
      readonly birth_date: string | null;
      city: string;
      /** @description ISO 3166-1 alpha-2 code, e.g. BJ or FR. */
      country?: string | null;
      preferred_language: components["schemas"]["LanguageEnum"];
      /** @description ISO 4217 code, e.g. XOF or EUR. */
      preferred_currency?: string | null;
      theme: components["schemas"]["ThemeEnum"];
      text_size: components["schemas"]["TextSizeEnum"];
      data_saver: boolean;
      /** @description Shows buttons that read important texts aloud. */
      audio_mode: boolean;
      /** WhatsApp notifications */
      notify_whatsapp: boolean;
      /** E-mail notifications */
      notify_email: boolean;
      /** Push notifications */
      notify_push: boolean;
      /** Format: time */
      quiet_hours_start?: string | null;
      /** Format: time */
      quiet_hours_end?: string | null;
      readonly roles: components["schemas"]["RolesEnum"][];
      readonly is_pro: boolean;
      readonly is_minor: boolean;
      readonly photo: components["schemas"]["Media"] | null;
      readonly has_password: boolean;
      readonly onboarding_required: boolean;
      /** Format: date-time */
      readonly created_at: string;
    };
    /** @description What the web app needs to show a media (see services.asset_payload). */
    Media: {
      /** Format: uuid */
      id: string;
      kind: components["schemas"]["KindEnum"];
      status: components["schemas"]["StatusEnum"];
      error: string | null;
      blurhash: string | null;
      width: number | null;
      height: number | null;
      /** Format: double */
      duration: number | null;
      urls: {
        [key: string]: string;
      };
    };
    MediaUploadRequest: {
      /** Format: binary */
      file: string;
      purpose: components["schemas"]["PurposeEnum"];
      kind?: components["schemas"]["KindEnum"];
    };
    /**
     * @description * `client` - client
     *     * `pro` - pro
     * @enum {string}
     */
    ModeEnum: "client" | "pro";
    Notification: {
      /** Format: uuid */
      readonly id: string;
      /** Event */
      event_key: string;
      title?: string;
      /** Text */
      body?: string;
      link?: string;
      readonly read: boolean;
      /** Format: date-time */
      readonly created_at: string;
    };
    Ok: {
      status: string;
    };
    OnboardingRequest: {
      mode: components["schemas"]["ModeEnum"];
      /** Format: date */
      birth_date: string;
      trades?: string[];
      language?: components["schemas"]["LanguageEnum"];
      city?: string;
    };
    PaginatedNotificationList: {
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
       */
      previous?: string | null;
      results: components["schemas"]["Notification"][];
    };
    PasswordLoginRequest: {
      identifier: string;
      password: string;
    };
    PasswordSetRequest: {
      password: string;
    };
    PatchedMeRequest: {
      first_name?: string;
      last_name?: string;
      city?: string;
      /** @description ISO 3166-1 alpha-2 code, e.g. BJ or FR. */
      country?: string | null;
      preferred_language?: components["schemas"]["LanguageEnum"];
      /** @description ISO 4217 code, e.g. XOF or EUR. */
      preferred_currency?: string | null;
      theme?: components["schemas"]["ThemeEnum"];
      text_size?: components["schemas"]["TextSizeEnum"];
      data_saver?: boolean;
      /** @description Shows buttons that read important texts aloud. */
      audio_mode?: boolean;
      /** WhatsApp notifications */
      notify_whatsapp?: boolean;
      /** E-mail notifications */
      notify_email?: boolean;
      /** Push notifications */
      notify_push?: boolean;
      /** Format: time */
      quiet_hours_start?: string | null;
      /** Format: time */
      quiet_hours_end?: string | null;
    };
    PhotoRequest: {
      /** Format: binary */
      photo: string;
    };
    /**
     * @description * `avatar` - avatar
     *     * `identity_document` - identity_document
     *     * `itinerary_video` - itinerary_video
     *     * `post` - post
     *     * `voice_note` - voice_note
     * @enum {string}
     */
    PurposeEnum: "avatar" | "identity_document" | "itinerary_video" | "post" | "voice_note";
    PushKey: {
      public_key: string | null;
    };
    PushKeysRequest: {
      p256dh: string;
      auth: string;
    };
    PushSubscribeRequest: {
      /** Format: uri */
      endpoint: string;
      keys: components["schemas"]["PushKeysRequest"];
    };
    PushUnsubscribeRequest: {
      /** Format: uri */
      endpoint: string;
    };
    /**
     * @description * `client` - Client
     *     * `pro` - Professional
     *     * `staff` - Staff
     * @enum {string}
     */
    RolesEnum: "client" | "pro" | "staff";
    SignIn: {
      created: boolean;
      /** @description The account was waiting to be deleted: signing in kept it. */
      deletion_cancelled: boolean;
      user: components["schemas"]["Me"];
    };
    /**
     * @description * `pending` - pending
     *     * `processing` - processing
     *     * `ready` - ready
     *     * `rejected` - rejected
     *     * `failed` - failed
     * @enum {string}
     */
    StatusEnum: "pending" | "processing" | "ready" | "rejected" | "failed";
    /**
     * @description * `normal` - Normal
     *     * `large` - Large
     *     * `xlarge` - Extra large
     * @enum {string}
     */
    TextSizeEnum: "normal" | "large" | "xlarge";
    /**
     * @description * `system` - Like the device
     *     * `light` - Light
     *     * `dark` - Dark
     * @enum {string}
     */
    ThemeEnum: "system" | "light" | "dark";
    Trade: {
      key: string;
      name: string;
      /** Pictogram */
      icon: components["schemas"]["IconEnum"];
    };
    UnreadCount: {
      unread: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_logout_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
    };
  };
  auth_logout_all_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
    };
  };
  auth_otp_request_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CodeRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["CodeRequestRequest"];
        "multipart/form-data": components["schemas"]["CodeRequestRequest"];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CodeRequestResult"];
        };
      };
    };
  };
  auth_otp_verify_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeVerifyRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["CodeVerifyRequest"];
        "multipart/form-data": components["schemas"]["CodeVerifyRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignIn"];
        };
      };
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignIn"];
        };
      };
    };
  };
  auth_password_login_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordLoginRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordLoginRequest"];
        "multipart/form-data": components["schemas"]["PasswordLoginRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignIn"];
        };
      };
    };
  };
  auth_refresh_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
    };
  };
  countries_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Country"][];
        };
      };
    };
  };
  guest_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Guest"];
        };
      };
    };
  };
  guest_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GuestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["GuestRequest"];
        "multipart/form-data": components["schemas"]["GuestRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Guest"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  me_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeletionScheduled"];
        };
      };
    };
  };
  me_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedMeRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedMeRequest"];
        "multipart/form-data": components["schemas"]["PatchedMeRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  me_contact_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ContactChangeRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["ContactChangeRequestRequest"];
        "multipart/form-data": components["schemas"]["ContactChangeRequestRequest"];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CodeRequestResult"];
        };
      };
    };
  };
  me_contact_confirm_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContactChangeConfirmRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["ContactChangeConfirmRequest"];
        "multipart/form-data": components["schemas"]["ContactChangeConfirmRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  me_onboarding_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OnboardingRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["OnboardingRequest"];
        "multipart/form-data": components["schemas"]["OnboardingRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  me_password_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordSetRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordSetRequest"];
        "multipart/form-data": components["schemas"]["PasswordSetRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
    };
  };
  me_photo_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["PhotoRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PhotoRequest"];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  me_photo_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  media_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["MediaUploadRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["MediaUploadRequest"];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Media"];
        };
      };
    };
  };
  media_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        asset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Media"];
        };
      };
    };
  };
  notifications_list: {
    parameters: {
      query?: {
        /** @description The pagination cursor value. */
        cursor?: string;
        /** @description Number of results to return per page. */
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedNotificationList"];
        };
      };
    };
  };
  notifications_push_key_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PushKey"];
        };
      };
    };
  };
  notifications_push_subscriptions_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushSubscribeRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PushSubscribeRequest"];
        "multipart/form-data": components["schemas"]["PushSubscribeRequest"];
      };
    };
    responses: {
      /** @description No response body */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  notifications_push_unsubscribe_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushUnsubscribeRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PushUnsubscribeRequest"];
        "multipart/form-data": components["schemas"]["PushUnsubscribeRequest"];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  notifications_read_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["MarkReadRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["MarkReadRequest"];
        "multipart/form-data": components["schemas"]["MarkReadRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnreadCount"];
        };
      };
    };
  };
  notifications_test_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  notifications_unread_count_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnreadCount"];
        };
      };
    };
  };
  trades_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Trade"][];
        };
      };
    };
  };
}
