# Generated by Django 5.2.17 on 2026-10-04 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_key', models.CharField(db_index=True, max_length=80, verbose_name='event')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='text')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='link')),
                ('in_app', models.BooleanField(default=True, verbose_name='shown in the app')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('channel', models.CharField(choices=[('in_app', 'In the app'), ('email', 'E-mail'), ('push', 'Phone alert (push)'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10, verbose_name='channel')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('skipped', 'Not sent (channel off)'), ('failed', 'Failed')], default='scheduled', max_length=10, verbose_name='status')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='text')),
                ('scheduled_for', models.DateTimeField(verbose_name='planned for')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='error')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'sending',
                'verbose_name_plural': 'sendings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_key', models.CharField(db_index=True, help_text='e.g. booking.confirmed', max_length=80, verbose_name='event')),
                ('channel', models.CharField(choices=[('in_app', 'In the app'), ('email', 'E-mail'), ('push', 'Phone alert (push)'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10, verbose_name='channel')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('title_sk', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('body', models.TextField(verbose_name='text')),
                ('body_fr', models.TextField(null=True, verbose_name='text')),
                ('body_en', models.TextField(null=True, verbose_name='text')),
                ('body_sk', models.TextField(null=True, verbose_name='text')),
                ('link', models.CharField(blank=True, help_text='Page opened on tap, e.g. /me', max_length=200, verbose_name='link')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='when is it sent?')),
            ],
            options={
                'verbose_name': 'notification template',
                'verbose_name_plural': 'notification templates',
                'ordering': ['event_key', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('event_key', 'channel'), name='notifications_template_unique_channel')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('endpoint', models.URLField(max_length=600, unique=True, verbose_name='address')),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='device')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='notifications_delivery_unique_channel'),
        ),
    ]
