# Generated by Django 5.2.17 on 2026-10-04 00:02

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='ISO 4217 code, e.g. XOF or EUR.', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a 3-letter ISO 4217 code.')], verbose_name='code')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('name_fr', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('name_sk', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('symbol', models.CharField(max_length=8, verbose_name='symbol')),
                ('decimal_places', models.PositiveSmallIntegerField(help_text='Number of decimals of the currency: 0 for XOF, 2 for EUR.', verbose_name='decimal places')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code, e.g. BJ or FR.', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use a 2-letter ISO 3166 code.')], verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_sk', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('phone_prefix', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\+\\d{1,4}$', 'Use the format +229.')], verbose_name='phone prefix')),
                ('default_language', models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('sk', 'Slovak')], default='fr', max_length=8, verbose_name='default language')),
                ('timezone', models.CharField(default='Europe/Paris', max_length=64, verbose_name='time zone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='core.currency', verbose_name='default currency')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('name_fr', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_sk', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_sk', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('client', 'Client'), ('pro', 'Professional'), ('staff', 'Staff')], max_length=16), blank=True, default=list, help_text='Leave empty to enable for every role.', size=None, verbose_name='roles')),
                ('countries', models.ManyToManyField(blank=True, help_text='Leave empty to enable in every country.', related_name='feature_flags', to='core.country', verbose_name='countries')),
            ],
            options={
                'verbose_name': 'feature flag',
                'verbose_name_plural': 'feature flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*(\\.[a-z0-9_]+)*$', 'Use lowercase words separated by dots, e.g. escrow.ship_deadline_days.')], verbose_name='key')),
                ('value_type', models.CharField(choices=[('string', 'Text'), ('integer', 'Whole number'), ('decimal', 'Decimal number'), ('boolean', 'Yes / no'), ('json', 'JSON')], default='string', max_length=16, verbose_name='type')),
                ('value', models.TextField(help_text='Booleans: true or false. Decimals use a dot: 12.5.', verbose_name='value')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_sk', models.TextField(blank=True, null=True, verbose_name='description')),
                ('country', models.ForeignKey(blank=True, help_text='Leave empty for the default value used in every country.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'platform setting',
                'verbose_name_plural': 'platform settings',
                'ordering': ['key', 'country__code'],
                'constraints': [models.UniqueConstraint(fields=('key', 'country'), name='core_platformsetting_unique_key_country', nulls_distinct=False)],
            },
        ),
    ]
