# Generated by Django 5.2.17 on 2026-10-04 20:54

import apps.core.media.models
import apps.core.media.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('action', models.CharField(db_index=True, max_length=80, verbose_name='action')),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='object id')),
                ('target_repr', models.CharField(blank=True, max_length=200, verbose_name='object')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='before')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='after')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='device')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='by')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='object type')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit journal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='core_audite_target__8596cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('image', 'Picture'), ('video', 'Video'), ('audio', 'Voice note')], max_length=8, verbose_name='type')),
                ('purpose', models.SlugField(max_length=40, verbose_name='use')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private (signed links)')], default='public', max_length=8, verbose_name='visibility')),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('processing', 'Processing'), ('ready', 'Ready'), ('rejected', 'Refused'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12, verbose_name='status')),
                ('original', models.FileField(max_length=255, storage=apps.core.media.storage.private_storage, upload_to=apps.core.media.models.original_upload_to, verbose_name='original file')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='content type')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='size')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='duration (s)')),
                ('variants', models.JSONField(blank=True, default=dict, verbose_name='variants')),
                ('blurhash', models.CharField(blank=True, max_length=64, verbose_name='blur preview')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='error')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'purpose'], name='core_mediaa_owner_i_e66795_idx')],
            },
        ),
    ]
