# Generated by Django 5.2.17 on 2026-10-04 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.SlugField(max_length=40, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('name_fr', models.CharField(max_length=80, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='name')),
                ('name_sk', models.CharField(max_length=80, null=True, verbose_name='name')),
                ('icon', models.CharField(choices=[('makeup', 'Lipstick'), ('hair', 'Comb'), ('braids', 'Braid'), ('nails', 'Nail polish'), ('sewing', 'Thread spool'), ('headwrap', 'Headwrap'), ('skincare', 'Cream jar')], max_length=20, verbose_name='pictogram')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'trade',
                'verbose_name_plural': 'trades',
                'ordering': ['position', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ProProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('independent', 'Independent'), ('business', 'Salon or business')], default='independent', max_length=12, verbose_name='type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_profile', to=settings.AUTH_USER_MODEL, verbose_name='account')),
                ('trades', models.ManyToManyField(blank=True, related_name='pros', to='pros.trade', verbose_name='trades')),
            ],
            options={
                'verbose_name': 'pro profile',
                'verbose_name_plural': 'pro profiles',
            },
        ),
    ]
