# Generated by Django 5.2.17 on 2026-10-04 00:10

import apps.accounts.managers
import apps.accounts.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='International format, e.g. +229 01 97 00 00 00.', max_length=128, null=True, region=None, unique=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='e-mail address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('preferred_language', models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('sk', 'Slovak')], default='fr', max_length=8, verbose_name='preferred language')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('client', 'Client'), ('pro', 'Professional'), ('staff', 'Staff')], max_length=16), default=apps.accounts.models.default_roles, size=None, verbose_name='roles')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Can sign in to the back office.', verbose_name='admin access')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.country', verbose_name='country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('preferred_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.currency', verbose_name='preferred currency')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('phone__isnull', False), ('email__isnull', False), _connector='OR'), name='accounts_user_phone_or_email', violation_error_message='Enter a phone number or an e-mail address.'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique', violation_error_message='A user with this e-mail address already exists.')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
