# Generated by Django 5.2.17 on 2026-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audio_mode',
            field=models.BooleanField(default=False, help_text='Shows buttons that read important texts aloud.', verbose_name='audio mode'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_saver',
            field=models.BooleanField(default=False, verbose_name='data saver'),
        ),
        migrations.AddField(
            model_name='user',
            name='text_size',
            field=models.CharField(choices=[('normal', 'Normal'), ('large', 'Large'), ('xlarge', 'Extra large')], default='normal', max_length=8, verbose_name='text size'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('system', 'Like the device'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=8, verbose_name='theme'),
        ),
    ]
