# Generated by Django 5.2.17 on 2026-10-04 18:53

import apps.accounts.models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_display_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('destination_kind', models.CharField(choices=[('phone', 'Phone'), ('email', 'E-mail')], max_length=8, verbose_name='destination type')),
                ('destination', models.CharField(max_length=254, verbose_name='destination')),
                ('destination_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('code_hash', models.CharField(editable=False, max_length=64)),
                ('channel', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'E-mail'), ('console', 'Console (development)')], max_length=10, verbose_name='channel')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('max_attempts', models.PositiveSmallIntegerField(verbose_name='maximum attempts')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('ip_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'one-time code',
                'verbose_name_plural': 'one-time codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.accounts.models.avatar_upload_to, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='e-mail verified at'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='e-mail notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_push',
            field=models.BooleanField(default=True, verbose_name='push notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_whatsapp',
            field=models.BooleanField(default=True, verbose_name='WhatsApp notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='welcome completed at'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='phone verified at'),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_channel',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'E-mail'), ('admin', 'Created in the admin')], max_length=8, verbose_name='sign-up channel'),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tokens revoked at'),
        ),
        migrations.CreateModel(
            name='GuestIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='converted at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_identities', to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'verbose_name': 'guest',
                'verbose_name_plural': 'guests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('method', models.CharField(choices=[('otp', 'One-time code'), ('password', 'Password')], max_length=10, verbose_name='method')),
                ('channel', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'E-mail'), ('console', 'Console (development)')], max_length=10, verbose_name='channel')),
                ('success', models.BooleanField(verbose_name='success')),
                ('failure_reason', models.CharField(blank=True, max_length=40, verbose_name='reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'sign-in',
                'verbose_name_plural': 'sign-in journal',
                'ordering': ['-created_at'],
            },
        ),
    ]
