# Generated by Django 5.2.17 on 2026-10-04 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpchallenge_user_avatar_user_city_user_deleted_at_and_more'),
        ('core', '0002_auditevent_mediaasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='code_encrypted',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='delivery_failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivery failed at'),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='planned_channels',
            field=models.JSONField(blank=True, default=list, verbose_name='channels to try'),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('sign_in', 'Sign-up or sign-in'), ('change_contact', 'New number or e-mail')], default='sign_in', max_length=16, verbose_name='purpose'),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent at'),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deletion requested at'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='quiet hours end'),
        ),
        migrations.AddField(
            model_name='user',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='quiet hours start'),
        ),
    ]
